### ISSUE TITLE
Cannot read file '/app/tsconfig.base.json'

### ISSUE THREAD

**Issue by ingramcomputers** [Nine-Minds/alga-psa#251]
I just came across your project and it looks really cool. I can't seem to get it to build on Ubuntu Server 24.04. I have gone through the setup guide several times. Even watched some of the old videos. 

` => ERROR [server 10/13] RUN npm run build                                                                                                                                                                                                    3.3s
------
 > [server 10/13] RUN npm run build:
0.833
0.833 > server@0.1.0 build
0.833 > NEXT_PUBLIC_EDITION=enterprise next build
0.833
2.076 Attention: Next.js now collects completely anonymous telemetry regarding usage.
2.077 This information is used to shape Next.js' roadmap and prioritize features.
2.077 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
2.077 https://nextjs.org/telemetry
2.077
2.238   ▲ Next.js 14.2.23
2.238   - Environments: .env
2.239
2.429    Creating an optimized production build ...
3.045
3.045 > Build error occurred
3.050 FatalError: error TS5083: Cannot read file '/app/tsconfig.base.json'.
3.050
3.050     at getTypeScriptConfiguration (/app/node_modules/next/dist/lib/typescript/getTypeScriptConfiguration.js:49:19)
3.050     at loadJsConfig (/app/node_modules/next/dist/build/load-jsconfig.js:112:91)
3.050     at async loadProjectInfo (/app/node_modules/next/dist/build/webpack-config.js:283:43)
3.050     at async /app/node_modules/next/dist/build/webpack-build/impl.js:137:22
3.050     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
3.050     at async webpackBuildImpl (/app/node_modules/next/dist/build/webpack-build/impl.js:136:21)
3.050     at async /app/node_modules/next/dist/build/index.js:1006:111
3.050     at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:154:20)
3.050     at async build (/app/node_modules/next/dist/build/index.js:368:9)
3.210 npm ERR! Lifecycle script `build` failed with error:
3.212 npm ERR! Error: command failed
3.214 npm ERR!   in workspace: server@0.1.0
3.215 npm ERR!   at location: /app/server
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
`

**Comment by RobertAtNineMinds** [comment]
This should be fixed by #256 and merged to main.
